### ISSUE TITLE
Please support relative path for Get-DecryptedAnsibleVault -Path and Get-EncryptedAnsibleVault -Path

### ISSUE THREAD

**Issue by tchia04** [jborean93/PowerShell-AnsibleVault#1]
If the vault.yml is in the current directory, this command doesn't work and causes lots of exception errors.

Get-DecryptedAnsibleVault -path vault.yml

It works fine if I specify the absolute path Get-DecryptedAnsibleVault -path c:\blahA\blahB\.....\vault.yml

Same issue applies to Get-EncryptedAnsibleVault -Path

cmdlet Get-DecryptedAnsibleVault at command pipeline position 1
Supply values for the following parameters:
Password: *********
<pre>
Exception calling "ReadAllText" with "1" argument(s): "Could not find file 'C:\Users\tchia\vault.yml'."
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:67 char:18
+         ByPath { [System.IO.File]::ReadAllText($Path) }
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:71 char:9
+     if (-not $vault_text.StartsWith('$ANSIBLE_VAULT;')) {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-VaultHeader : Cannot bind argument to parameter 'Value' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:75 char:68
+     $version, $cipher, $id, $cipher_bytes = Get-VaultHeader -Value $vault_text
+                                                                    ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-VaultHeader], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-VaultHeader

Split-Byte : Cannot bind argument to parameter 'Value' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:79 char:56
+     $salt, $hmac, $encrypted_bytes = Split-Byte -Value $cipher_bytes -Char ([cha ...
+                                                        ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Byte], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Split-Byte

Exception calling "GetString" with "1" argument(s): "Array cannot be null.
Parameter name: bytes"
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:81 char:5
+     $salt = Convert-HexToByte -Value ([System.Text.Encoding]::UTF8.GetString($sa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Exception calling "GetString" with "1" argument(s): "Array cannot be null.
Parameter name: bytes"
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:82 char:5
+     $expected_hmac = [System.Text.Encoding]::UTF8.GetString($hmac)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Exception calling "GetString" with "1" argument(s): "Array cannot be null.
Parameter name: bytes"
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:83 char:5
+     $encrypted_bytes = Convert-HexToByte -Value ([System.Text.Encoding]::UTF8.Ge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

New-VaultKey : Cannot bind argument to parameter 'Salt' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:85 char:77
+     $cipher_key, $hmac_key, $nonce = New-VaultKey -Password $password -Salt $sal ...
+                                                                             ~~~~
    + CategoryInfo          : InvalidData: (:) [New-VaultKey], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,New-VaultKey

Get-HMACValue : Cannot bind argument to parameter 'Value' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:87 char:41
+     $actual_hmac = Get-HMACValue -Value $encrypted_bytes -Key $hmac_key
+                                         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-HMACValue], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-HMACValue

Invoke-AESCTRCycle : Cannot bind argument to parameter 'Value' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:92 char:50
+     $decrypted_bytes = Invoke-AESCTRCycle -Value $encrypted_bytes -Key $cipher_k ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-AESCTRCycle], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Invoke-AESCTRCycle

Remove-Pkcs7Padding : Cannot bind argument to parameter 'Value' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:96 char:50
+     $unpadded_bytes = Remove-Pkcs7Padding -Value $decrypted_bytes -BlockSize 128
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Pkcs7Padding], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Remove-Pkcs7Padding

Exception calling "GetString" with "1" argument(s): "Array cannot be null.
Parameter name: bytes"
At C:\Program Files\WindowsPowerShell\Modules\AnsibleVault\Public\Get-DecryptedAnsibleVault.ps1:97 char:5
+     $decrypted_string = $Encoding.GetString($unpadded_bytes)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException
</pre>

**Comment by jborean93** [comment]
Hmm, I see what you mean, should be a simple fix.

**Comment by jborean93** [comment]
@tchia04 this has been fixed with https://github.com/jborean93/PowerShell-AnsibleVault/pull/2. I'll make a release of the PS Gallery sometime shortly. Thanks for posting the issue.
