### ISSUE TITLE
Faile to install

### ISSUE THREAD

**Issue by tguenneguez** [jborean93/PowerShell-AnsibleVault#11]
When I try to install, I have an error :
Install-Module -Name AnsibleVault -Scope CurrentUser

Référentiel non approuvé
Vous installez les modules à partir d'un référentiel non approuvé. Si vous approuvez ce référentiel, modifiez sa valeur
 InstallationPolicy en exécutant l'applet de commande Set-PSRepository. Voulez-vous vraiment installer les modules à
partir de PSGallery ?
[O] Oui  [T] Oui pour tout  [N] Non  [U] Non pour tout  [S] Suspendre  [?] Aide (la valeur par défaut est « N ») : O
PackageManagement\Install-Package : Une erreur s'est produite lors du chargement du module de script AnsibleVault, car
celui-ci présente un mode de langage différent du module du manifeste. Le mode de langage du manifeste est
ConstrainedLanguage et le mode de langage du module est FullLanguage. Assurez-vous que tous les fichiers du module
sont signés ou, dans le cas contraire, qu'il font partie de la configuration de la liste verte de votre application.
Au caractère C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 : 21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
    Exception
    + FullyQualifiedErrorId : Modules_MismatchedLanguageModes,Microsoft.PowerShell.Commands.TestModuleManifestCommand,
   Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by ijioio** [comment]
I suppose it is related to the execute policies of the PowerShell. First check what policies you have:

```shell
> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       Undefined
```

By default all policies has value `Undefined`. If all policies set as `Undefined` the result policy will fallback to `Restricted` value, means you can't execute scripts (see [Execution Policy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.4#-executionpolicy) for policies description). In that case let's assign a `Bypass` policy to the local machine that will allow to run any scripts without blocking:

```shell
> Set-ExecutionPolicy -ExecutionPolicy Bypass
```

On the user prompt enter `Y` and press `Enter` to confirm. Now if you check the list of policies again it should become like that:

```shell
> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine          Bypass
```

Now we can install `AnsibleVault` module with the following command:

```shell
> Install-Module -Name AnsibleVault
```

**Comment by tguenneguez** [comment]
Thanks for reply but 2 years after so I doesn't know where I try to use this think...
