### ISSUE TITLE
Trailing whitespace line at bottom when Decrypted

### ISSUE THREAD

**Issue by C-Bam** [jborean93/PowerShell-AnsibleVault#3]
Hi,

thanks for this brillant module !

There is a little catch when you Encrypt and Decrypt back and forth

An extra line is added each time to the decrypted text.

```yaml
vault_pass: "plumbus"
```
```yaml
vault_pass: "plumbus"
[empty line]
```
```yaml
vault_pass: "plumbus"
[empty line]
[empty line]
```

and so on...

**Comment by jborean93** [comment]
Hi, thanks for the issue but I'm not able to replicate this

```
$pass = ConvertTo-SecureString -AsPlainText -Force -String password
Get-EncryptedAnsibleVault -Value 'vault_pass: "plumbus"' -Password $pass | `
    Get-DecryptedAnsibleVault -Password $pass | `
    Get-EncryptedAnsibleVault -Password $pass | `
    Get-DecryptedAnsibleVault -Password $pass
```

The above code takes in a string value and encrypts it in 2 cycles and the output vault is the same as the input value. Are you able to give me a self contained script that will replicate the issue you are seeing?

**Comment by maksymgendin** [comment]
Facing the same issue here

**Comment by jborean93** [comment]
@maksymgendin do you have a reproducer for this? I'm unable to replicate it locally and I don't see where I could be adding a stray newline.

**Comment by maksymgendin** [comment]
@jborean93 
```
$ANSIBLE_VAULT;1.1;AES256
37656232396638653738643265323733323231343261326530303433386234383763323330346630
6265653663613838353231316361383535393139623065610a636563653062336530666439303535
62316133373535383362356261393333313039626238623535633634616665633462623835323939
3835613230323133330a383163353765366664373261363362623836666264363464643334346630
6662
```
Here is an encrypted payload with dummy content:
```
---

```
The password is `tst`. After each decryption there is a new line added...for decryption I use these commands:
```
$pwd = ConvertTo-SecureString -AsPlainText -Force -String tst
Get-DecryptedAnsibleVault -Path FILE_PATH -Password $pwd | Set-Content -Path FILE_PATH
```
For encryption these:
```
$pwd = ConvertTo-SecureString -AsPlainText -Force -String tst
Get-EncryptedAnsibleVault -Path FILE_PATH -Password $pwd | Set-Content -Path FILE_PATH
```

**Comment by maksymgendin** [comment]
@jborean93 Or maybe the new line is added on encryption, not sure about that actually

**Comment by C-Bam** [comment]
@jborean93  It seems to be related with saving and loading from a file. It seems I have found a workaround

@maksymgendin Can you try 
```powershell
$pwd = ConvertTo-SecureString -AsPlainText -Force -String tst
Get-EncryptedAnsibleVault -Path FILE_PATH -Password $pwd | Set-Content -Path FILE_PATH -NoNewLine
```

The `-NoNewLine` should solve our issue

**Comment by maksymgendin** [comment]
@C-Bam Seems to work, thank you so much!

**Comment by jborean93** [comment]
Thanks for looking into this, I agree that this is the issue and using `-NoNewLine` solves it. If using an older PowerShell version you can also do `[System.IO.File]::WriteAllText($path, $vault_text)` but that's not as nice as what pipelining can give you.
